FROM golang:1.8 AS build-stage
WORKDIR /go/src/github.com/codeship/go-hello-world
COPY hello-world.go .
RUN go build -o hello-world .


FROM alpine:latest
COPY --from=build-stage /go/src/github.com/codeship/go-hello-world/hello-world /bin
CMD ["hello-world"]
